[spec]
specname = "API_Errors"
file = "API_Errors.sp.h"
FELISINTERNALS = true
[includes."<API.h>"]

[decl.Enum."API_Error"]
StringMapping = true
Fields."Ok" = 0
Fields."Alloc" = 1
Fields."InvalidArgument" = 2
Fields."PlugError" = 3
Fields."InvalidPermissions" = 4
Fields."NotFound" = 5

[decl.Function."API_strerror"]
Params."error_code" = "INT"
ReturnType = "const char *"
Attributes = "FPKG_API_PUBLIC"
